### ISSUE TITLE
Readme file text blacked out

### ISSUE THREAD

**Issue by Laserbolt** [Laserbolt/Bluej-Theme-Hub#2]
The text in the readme file in the project window is black along with the background.

**Comment by Chroxium** [comment]
Unable to fix Unfortunately, the font color of the editor of text files seems to be inbuilt as it does not seem to accept any changes from either cssfx or scenicView. The issue will be fixed if either I am mistaken and can simply not figure out the class name or if the text color is fixed to match the default text color
